// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/accounts": {
            "get": {
                "description": "Get accounts for a given item ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get accounts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "item_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Account"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid item ID",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "Check the health of the server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/plaid/exchange-public-token": {
            "post": {
                "description": "Exchanges a Link public_token server-side, stores the encrypted access token and item, then fetches and persists the user's accounts from Plaid.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plaid"
                ],
                "summary": "Exchange Plaid public token",
                "parameters": [
                    {
                        "description": "public_token from Link onSuccess",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ExchangePublicTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PlaidExchangePublicTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body or unknown fields",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Content-Type (allowed: application/json, text/xml)",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Plaid or server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/plaid/items": {
            "get": {
                "description": "Returns all linked Plaid items with their synced accounts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plaid"
                ],
                "summary": "List linked institutions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.PlaidItemSummary"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/plaid/items/{id}/link-token": {
            "get": {
                "description": "Returns a Plaid link token configured for account selection update mode for an existing item.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plaid"
                ],
                "summary": "Create update-mode link token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plaid item UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "link token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/plaid/items/{id}/sync-accounts": {
            "post": {
                "description": "Re-fetches accounts from Plaid for an existing item and upserts them (soft sync — adds new, updates existing, never deletes).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plaid"
                ],
                "summary": "Sync accounts for an item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plaid item UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PlaidExchangePublicTokenResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/plaid/link-token": {
            "get": {
                "description": "Create a Plaid link token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plaid"
                ],
                "summary": "Create Plaid link token",
                "responses": {
                    "200": {
                        "description": "plaid-sandbox-1234567890",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "415": {
                        "description": "Unsupported Content-Type (allowed: application/json, text/xml)",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Plaid or server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Account": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string",
                    "example": "1234567890"
                },
                "available_balance": {
                    "type": "number",
                    "example": 1000
                },
                "created_at": {
                    "type": "string",
                    "example": "2021-01-01T00:00:00Z"
                },
                "currency_code": {
                    "type": "string",
                    "example": "USD"
                },
                "current_balance": {
                    "type": "number",
                    "example": 1000
                },
                "id": {
                    "type": "string",
                    "example": "1234567890"
                },
                "name": {
                    "type": "string",
                    "example": "Checking Account"
                },
                "plaid_item_id": {
                    "type": "string",
                    "example": "1234567890"
                },
                "subtype": {
                    "type": "string",
                    "example": "checking"
                },
                "type": {
                    "type": "string",
                    "example": "checking"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2021-01-01T00:00:00Z"
                }
            }
        },
        "domain.AccountSummary": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string",
                    "example": "1234567890"
                },
                "name": {
                    "type": "string",
                    "example": "Checking Account"
                },
                "subtype": {
                    "type": "string",
                    "example": "checking"
                },
                "type": {
                    "type": "string",
                    "example": "checking"
                }
            }
        },
        "domain.PlaidItemSummary": {
            "type": "object",
            "properties": {
                "accounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.AccountSummary"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "1234567890"
                },
                "institution_id": {
                    "type": "string",
                    "example": "1234567890"
                }
            }
        },
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "The server encountered a problem and could not process your request"
                }
            }
        },
        "main.ExchangePublicTokenRequest": {
            "type": "object",
            "properties": {
                "public_token": {
                    "type": "string",
                    "example": "public-sandbox-abc123"
                }
            }
        },
        "main.PlaidExchangePublicTokenResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "linked"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
