info:
  contact: {}
paths:
  /api/v1/plaid/link-token:
    get:
      consumes:
      - application/json
      description: Create a Plaid link token
      produces:
      - application/json
      responses:
        "200":
          description: Plaid link token
          schema:
            type: string
      summary: Create Plaid link token
      tags:
      - plaid
  /health:
    get:
      consumes:
      - application/json
      description: Check the health of the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
swagger: "2.0"
